[profile.default]
solc = "0.8.19"
src = "src"
out = "out"
libs = ["lib"]
optimizer_runs = 1_000_000
verbosity = 3

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
